# Enable C++ support
language: cpp

# Compiler selection
compiler:
  - gcc

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9

script:
  - export CC=gcc-4.9
  - export CXX=g++-4.9
  - mkdir build
  - cd build
  - cmake .. && make && make test
